version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - adminboard

  php:
    image: masumonline/php-fpm-buster-8.1:6
    working_dir: /var/www/html
    user: "1000:1000"
    volumes:
      - ./src:/var/www/html
      - ./php/ini/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - PHP_MEMORY_LIMIT=1024M
      - upload_max_filesize=20M
      - post_max_size=20M
    networks:
      - adminboard

  composer:
    image: composer:latest
    user: "1000:1000"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - adminboard

  npm:
    image: node:13.7
    user: "1000:1000"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
        - adminboard

  artisan:
    image: masumonline/php-fpm-buster-8.1:latest
    user: "1000:1000"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - adminboard

networks:
  adminboard:
