version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "8089:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb
    networks:
      - newcomcity

  php:
    image: masumonline/php-fpm-buster-8.1:latest
    working_dir: /var/www/html
    user: "1000:1000"
    volumes:
      - ./src:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=1024M
    networks:
      - newcomcity

  mariadb:
    image: mariadb:10.5
    restart: always
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: UrXc3whE2q2U5MZfnet
      MYSQL_DATABASE: gear
    volumes:
      - ./db/:/var/lib/mysql/
    networks:
      - newcomcity
 
  adminer:
    image: michalhosna/adminer
    restart: always
    ports:
      - 8079:8080
    environment:
      ADMINER_PASSWORD: UrXc3whE2q2U5MZfnet
      ADMINER_SERVER: mariadb
      ADMINER_USERNAME: root
    networks:
      - newcomcity

  composer:
    image: composer:latest
    container_name: composer
    user: "1000:1000"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - newcomcity

  npm:
    image: node:13.7
    container_name: npm
    user: "1000:1000"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
        - newcomcity

  artisan:
    image: masumonline/php-fpm-buster-8.1:latest
    container_name: artisan
    user: "1000:1000"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mariadb
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - newcomcity

networks:
  newcomcity: